### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by KingOfNoobs** [paytm/Paytm_PHP_Checksum#3]
Hi, I just manually downloaded and called **PaytmChecksum.php**  by `require_once("app/Paytm/paytmchecksum/PaytmChecksum.php");`

But I received the following error mentioned below:
```
ErrorException in PaytmChecksum.php line 126:
Array and string offset access syntax with curly braces is deprecated
in PaytmChecksum.php line 126
```
Php version details
```
php -v
PHP 7.4.9 (cli) (built: Aug  4 2020 11:52:41) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
``` 

Plesae use square braces for array instead of curly braces.
Change `$pad = ord($text{strlen($text) - 1});` to `$pad = ord($text[strlen($text) - 1]);` in line number 126 in PaytmChecksum.php

**Comment by LalitChaudhary1** [comment]
@KingOfNoobs Thanks! Updated.
